### PR TITLE
[FIX][SC-40682] Keyboard navigation for month year picker

### PR DESCRIPTION
**Pull request by KevinFabre-ods**
Vertical keyboard navigation (Up & Down) was wrong for 4 and 2 months columns layout

(Internal) Associated shortcut story: [sc-40682](https://app.shortcut.com/opendatasoft/story/40682/dateinput-fix-keyboard-navigation-for-month-calendar)

Associated issue: https://github.com/Hacker0x01/react-datepicker/issues/3927

### CODE REVIEW

**Review by wmai — CHANGES_REQUESTED** [review]
It appears that the algorithm isn't working perfectly as it is. If you want to reproduce the bug, you have to go to the month of September and press the down arrow.

I have this version of the algorithm (not necessarily more readable, I concede) which is based more on calculating position in a given matrix, rather than managing the different special cases. What do you think?

``` JavaScript
  moveDateByMonths = (date, months) => months < 0
    ? utils.subMonths(date, Math.abs(months))
    : utils.addMonths(date, months);

  onMonthKeyDown = (event, month) => {
    const {
      selected,
      preSelection,
      disabledKeyboardNavigation,
      showTwoColumnMonthYearPicker,
      showFourColumnMonthYearPicker,
      setPreSelection,
    } = this.props;
    event.preventDefault();
    const eventKey = event.key;
    const monthColumnsLayout = getMonthColumnsLayout(
      showFourColumnMonthYearPicker,
      showTwoColumnMonthYearPicker
    );

    const rows = MONTH_COLUMNS[monthColumnsLayout].grid.length;
    const cols = MONTH_COLUMNS[monthColumnsLayout].verticalNavigationOffset;
    let x = Math.floor(month / cols);
    let y = month % cols;
    let newDate = null;
    let newMonth = null;
    let monthsChange = 0;

    if (!disabledKeyboardNavigation) {
      switch (eventKey) {
        case "Enter":
          this.onMonthClick(event, month);
          setPreSelection(selected);
          break;
        case "ArrowRight":
          y = (y + 1) % cols;
          // Move to next row if needed
          x = x + (y === 0 ? 1 : 0);
          monthsChange = 1;
          break;
        case "ArrowLeft":
          y = (y - 1 + cols) % cols;
          // Move to previous row if needed
          x = x - (y === cols - 1 ? 1 : 0);
          monthsChange = -1;
          break;
        case "ArrowUp":
          x = (x - 1 + rows) % rows;
          monthsChange = -cols;
          break;
        case "ArrowDown":
          x = (x + 1) % rows;
          monthsChange = cols;
          break;
      }
      // Make sure that the new month is always positive
      newMonth = (((x * cols + y) % 12) + 12) % 12;
      newDate = this.moveDateByMonths(preSelection, monthsChange);
      this.handleMonthNavigation(newMonth, newDate);
    }
  };
```

**Comment by KevinFabre-ods** [comment]
Yes, It was expected. I'll do it

**Comment by KevinFabre-ods** [comment]
Thanks for the tests, I should have been more careful when I tested it.

The bug was in the ternary check for the ArrowDown and ArrowUp cases; It wasn't based on the month layout.
With https://github.com/opendatasoft/react-datepicker/pull/1/commits/a32b50a57162486cbb5227fdfc0c6828d8e20738, we're starting to use the matrix to check position while maintaining readability. What do you think?

**Review by wmai — APPROVED** [review]

**Comment by wmai** [comment]
> ...maintaining readability. What do you think?

Going back on this PR, the code is indeed more readable the way you've done it. Playing with modulos may look "fancy" but it's harder to understand ^^ LGTM

**Comment by KevinFabre-ods** [comment]
Closing this PR as it has been merged in the main repo https://github.com/Hacker0x01/react-datepicker/pull/4037

**Pull request closed without merging**
